apiVersion: batch/v1
kind: Job
metadata:
  name: echo-command
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine
        command:
          - echo
          - "Kelsen Brito's Job"
      restartPolicy: OnFailure # required
  ttlSecondsAfterFinished: 0 # deleta imediatamente

# job é imutável. Não é possível dar apply depois de mudanças
# por isso, é usado o ttlSecondsAfterFinished para deletá-lo automaticament