apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ro
  namespace: ingress-nginx
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ro
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ro
subjects:
- kind: ServiceAccount
  name: kubectl # Name is case sensitive
  namespace: default