apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 10% # padrão 25%
     maxUnavailable: 0 # padrão 25%. 
     # somente após os 10% começa a desfazer os antigos.
