apiVersion: v1
data:
  password: MTIz
  username: a2Vsc2Vu
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth

# k create secret generic secret-basic-auth --type=kubernetes.io/basic-auth --from-literal=extra=demo
# The Secret "secret-basic-auth" is invalid:
# * data[username]: Required value
# * data[password]: Required value


# Comando correto
# ❯ k create secret generic secret-basic-auth --type=kubernetes.io/basic-auth --from-literal=username=kelsen --from-literal=password=123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: USERNAME 
            valueFrom:
              secretKeyRef:
                name: secret-basic-auth
                key: username
          - name: PASSWORD 
            valueFrom:
              secretKeyRef:
                name: secret-basic-auth
                key: password
        volumeMounts:
          - name: secret-volume
            mountPath: "/tmp"
            readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-basic-auth 

# /volume/
#   ├── password      (arquivo)
#   ├── username      (arquivo)